"""
Visualisation module for WhatsApp conversation analysis.

Generates individual charts and self-contained HTML reports from the
pipeline results dict. All heavy imports (matplotlib, seaborn, wordcloud,
jinja2) are lazy so the module loads instantly even when extras are absent.

Output: matplotlib Figure objects for individual plots; Path to HTML file
        for report methods.
"""

from __future__ import annotations

import base64
import io
import logging
from pathlib import Path
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from matplotlib.figure import Figure

logger = logging.getLogger(__name__)

_WEEKDAYS = [
    "Monday", "Tuesday", "Wednesday", "Thursday",
    "Friday", "Saturday", "Sunday",
]

# Self-contained HTML template — no external CDN references.
_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>WhatsApp Analysis — {{ group_name }}</title>
  <style>
    *{box-sizing:border-box;margin:0;padding:0}
    body{font-family:system-ui,sans-serif;background:#f5f5f5;color:#333;padding:2rem}
    header{background:#075e54;color:#fff;padding:1.5rem 2rem;border-radius:8px;margin-bottom:2rem}
    header h1{font-size:1.6rem;font-weight:600}
    header p{opacity:.85;margin-top:.3rem}
    .section{background:#fff;border-radius:8px;padding:1.5rem;margin-bottom:1.5rem;
             box-shadow:0 1px 3px rgba(0,0,0,.12)}
    .section h2{font-size:1.1rem;color:#075e54;margin-bottom:1rem;
                border-bottom:1px solid #e0e0e0;padding-bottom:.5rem}
    .section img{max-width:100%;display:block;margin:0 auto}
    footer{text-align:center;margin-top:2rem;color:#999;font-size:.85rem}
  </style>
</head>
<body>
  <header>
    <h1>WhatsApp Analysis Report</h1>
    <p>Group: {{ group_name }}</p>
  </header>
  {% for section in sections %}
  <div class="section">
    <h2>{{ section.title }}</h2>
    <img src="data:image/png;base64,{{ section.image }}" alt="{{ section.title }}">
  </div>
  {% endfor %}
  <footer>Generated by whatsapp-analyser</footer>
</body>
</html>
"""


def _fig_to_base64(fig: Any) -> str:
    """Encode a matplotlib Figure as a base64 PNG string and close it."""
    import matplotlib.pyplot as plt

    buf = io.BytesIO()
    fig.savefig(buf, format="png", bbox_inches="tight", dpi=100)
    buf.seek(0)
    data = base64.b64encode(buf.read()).decode("utf-8")
    plt.close(fig)
    return data


class Visualizer:
    """Generate charts and self-contained HTML reports from pipeline results."""

    def plot_topic_distribution(self, results: dict) -> Figure:
        """
        Return a horizontal bar chart of topic weights.

        Args:
            results: Pipeline results dict (must contain 'topics').

        Returns:
            matplotlib Figure.
        """
        import matplotlib.pyplot as plt

        fig, ax = plt.subplots(figsize=(10, 5))
        topics_result = results.get("topics")

        if topics_result is None:
            ax.text(0.5, 0.5, "No topic data available",
                    ha="center", va="center", transform=ax.transAxes)
            return fig

        gt = topics_result["group_topics"].sort_values("weight", ascending=True)
        ax.barh(gt["topic_label"], gt["weight"], color="#4C72B0")
        ax.set_xlabel("Weight")
        ax.set_title("Topic Distribution")
        fig.tight_layout()
        return fig

    def plot_wordcloud(self, results: dict, topic_id: int = 0) -> Figure:
        """
        Return a word cloud (or bar chart fallback) for a single topic.

        Args:
            results:  Pipeline results dict (must contain 'topics').
            topic_id: Which topic to render.

        Returns:
            matplotlib Figure.
        """
        import matplotlib.pyplot as plt

        fig, ax = plt.subplots(figsize=(10, 5))
        ax.axis("off")

        topics_result = results.get("topics")
        if topics_result is None:
            ax.text(0.5, 0.5, "No topic data available",
                    ha="center", va="center", transform=ax.transAxes)
            return fig

        gt = topics_result["group_topics"]
        row = gt[gt["topic_id"] == topic_id]
        if row.empty:
            ax.text(0.5, 0.5, f"Topic {topic_id} not found",
                    ha="center", va="center", transform=ax.transAxes)
            return fig

        label = row.iloc[0]["topic_label"]
        words = [w.strip() for w in label.split(" / ")]
        word_freq = {w: max(1, len(words) - i) for i, w in enumerate(words)}

        try:
            from wordcloud import WordCloud
            wc = WordCloud(width=800, height=400, background_color="white")
            wc.generate_from_frequencies(word_freq)
            ax.imshow(wc, interpolation="bilinear")
        except ImportError:
            logger.warning("wordcloud not installed; rendering bar chart instead.")
            ax.axis("on")
            ax.bar(list(word_freq.keys()), list(word_freq.values()), color="#4C72B0")

        ax.set_title(f"Topic {topic_id}: {label}")
        fig.tight_layout()
        return fig

    def plot_sentiment_timeline(self, results: dict) -> Figure:
        """
        Return a line chart of mean daily sentiment over time.

        Args:
            results: Pipeline results dict (must contain 'sentiment').

        Returns:
            matplotlib Figure.
        """
        import matplotlib.pyplot as plt

        fig, ax = plt.subplots(figsize=(12, 4))
        sentiment_result = results.get("sentiment")

        if sentiment_result is None:
            ax.text(0.5, 0.5, "No sentiment data available",
                    ha="center", va="center", transform=ax.transAxes)
            return fig

        df = sentiment_result["df"].copy()
        df = df.sort_values("timestamp")
        daily = df.groupby(df["timestamp"].dt.normalize())["sentiment_score"].mean()

        ax.plot(daily.index, daily.values, linewidth=2, color="#4C72B0")
        ax.axhline(0, color="gray", linestyle="--", linewidth=0.8)
        ax.fill_between(daily.index, daily.values, 0,
                        where=(daily.values >= 0), alpha=0.3, color="green",
                        label="Positive")
        ax.fill_between(daily.index, daily.values, 0,
                        where=(daily.values < 0), alpha=0.3, color="red",
                        label="Negative")
        ax.set_xlabel("Date")
        ax.set_ylabel("Mean Sentiment Score")
        ax.set_title("Sentiment Over Time")
        ax.legend()
        fig.tight_layout()
        return fig

    def plot_user_activity(self, results: dict) -> Figure:
        """
        Return a horizontal bar chart of message count per author.

        Args:
            results: Pipeline results dict (must contain 'df_clean').

        Returns:
            matplotlib Figure.
        """
        import matplotlib.pyplot as plt

        fig, ax = plt.subplots(figsize=(10, 5))
        df = results.get("df_clean")

        if df is None:
            ax.text(0.5, 0.5, "No message data available",
                    ha="center", va="center", transform=ax.transAxes)
            return fig

        counts = df["author"].value_counts().sort_values(ascending=True)
        ax.barh(counts.index, counts.values, color="#4C72B0")
        ax.set_xlabel("Message Count")
        ax.set_title("Messages per User")
        fig.tight_layout()
        return fig

    def plot_hourly_heatmap(self, results: dict) -> Figure:
        """
        Return a heatmap of activity by weekday and hour.

        Args:
            results: Pipeline results dict (must contain 'temporal').

        Returns:
            matplotlib Figure.
        """
        import matplotlib.pyplot as plt
        import seaborn as sns

        fig, ax = plt.subplots(figsize=(16, 5))
        temporal = results.get("temporal")

        if temporal is None:
            ax.text(0.5, 0.5, "No temporal data available",
                    ha="center", va="center", transform=ax.transAxes)
            return fig

        sns.heatmap(temporal["hourly_heatmap"], ax=ax, cmap="YlOrRd",
                    linewidths=0.3, cbar_kws={"label": "Message Count"})
        ax.set_title("Activity by Hour and Day of Week")
        ax.set_xlabel("Hour of Day")
        ax.set_ylabel("Day of Week")
        fig.tight_layout()
        return fig

    def generate_report(self, results: dict, output_dir: Path) -> Path:
        """
        Generate a self-contained HTML report with all charts embedded as base64 PNG.

        Args:
            results:    Pipeline results dict.
            output_dir: Directory where report.html will be written.

        Returns:
            Path to the written report.html file.
        """
        from jinja2 import Template

        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)

        group_name = results.get("group_name", "Unknown Group")

        plots: list[tuple[str, Any]] = [
            ("Topic Distribution", self.plot_topic_distribution(results)),
            ("Messages per User", self.plot_user_activity(results)),
            ("Sentiment Over Time", self.plot_sentiment_timeline(results)),
            ("Hourly Activity Heatmap", self.plot_hourly_heatmap(results)),
        ]

        topics_result = results.get("topics")
        if topics_result is not None:
            for tid in topics_result["group_topics"]["topic_id"]:
                plots.append((
                    f"Word Cloud — Topic {int(tid)}",
                    self.plot_wordcloud(results, topic_id=int(tid)),
                ))

        sections = [
            {"title": title, "image": _fig_to_base64(fig)}
            for title, fig in plots
        ]

        html = Template(_HTML_TEMPLATE).render(
            group_name=group_name, sections=sections
        )

        output_path = output_dir / "report.html"
        output_path.write_text(html, encoding="utf-8")
        logger.info("Report written to %s", output_path)
        return output_path

    def generate_comparison_report(self, analyzers: list, output_dir: Path) -> Path:
        """
        Generate a self-contained HTML comparison report for multiple groups.

        Args:
            analyzers:  List of WhatsAppAnalyzer instances with a ._results attribute.
            output_dir: Directory where comparison_report.html will be written.

        Returns:
            Path to the written comparison_report.html file.
        """
        from jinja2 import Template

        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)

        fig = self._plot_topic_comparison(analyzers)
        sections = [{"title": "Topic Comparison Across Groups",
                     "image": _fig_to_base64(fig)}]

        html = Template(_HTML_TEMPLATE).render(
            group_name="Group Comparison", sections=sections
        )

        output_path = output_dir / "comparison_report.html"
        output_path.write_text(html, encoding="utf-8")
        logger.info("Comparison report written to %s", output_path)
        return output_path

    def _plot_topic_comparison(self, analyzers: list) -> Figure:
        """Return a grouped bar chart comparing topic weights across groups."""
        import matplotlib.pyplot as plt

        fig, ax = plt.subplots(figsize=(12, 6))

        for az in analyzers:
            results = getattr(az, "_results", {})
            topics_result = results.get("topics")
            group_name = results.get("group_name", "Unknown")
            if topics_result is None:
                continue
            gt = topics_result["group_topics"]
            ax.bar(gt["topic_label"], gt["weight"], label=group_name, alpha=0.7)

        ax.set_xlabel("Topic")
        ax.set_ylabel("Weight")
        ax.set_title("Topic Distribution Comparison")
        ax.legend()
        fig.tight_layout()
        return fig
